import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  view: {
    flex: 1,
    backgroundColor: "#fff",
    overflow: "hidden",
  },
  headerBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: "#ff9b63",
    height: 160,
  },
  backNavs: {
    position: "absolute",
    top: 60,
    left: 20,
    height: 40,
    width: 40,
    zIndex: 10,
  },
  backNavsChild: {
    height: 40,
    width: 40,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  backArrow: {
    fontSize: 28,
    color: "#fff",
    fontWeight: "bold",
  },
  mainTitle: {
    position: "absolute",
    top: 60,
    left: 0,
    right: 0,
    fontSize: 27,
    color: "#fff",
    fontFamily: "Poppins-Bold",
    fontWeight: "700",
    textAlign: "center",
  },
  greenContainer: {
    position: "absolute",
    top: 140,
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    backgroundColor: "#ebfff4",
    paddingTop: 30,
    paddingHorizontal: 20,
  },
  scrollContent: {
    flex: 1,
    paddingBottom: 150,
  },
  card: {
    width: "100%",
    marginBottom: 18,
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  cardInner: {
    minHeight: 80,
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  iconPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#f7f8f8",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  cardTextContainer: {
    flex: 1,
    justifyContent: "center",
  },
  cardLabel: {
    fontSize: 13,
    color: "#92a3a3",
    fontFamily: "Poppins-Regular",
    marginBottom: 4,
  },
  cardValue: {
    fontSize: 16,
    color: "#1d1617",
    fontFamily: "Poppins-SemiBold",
    fontWeight: "600",
    lineHeight: 24,
  },
  editSection: {
    marginTop: 20,
    marginBottom: 30,
  },
  editCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    marginBottom: 18,
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  editLabel: {
    fontSize: 15,
    color: "#1d1617",
    fontFamily: "Poppins-SemiBold",
    fontWeight: "600",
    marginBottom: 12,
  },
  editInput: {
    backgroundColor: "#f7f8f8",
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    color: "#1d1617",
    fontFamily: "Poppins-Regular",
  },
  editInputMultiline: {
    height: 90,
    textAlignVertical: "top",
  },
  datePickerButton: {
    backgroundColor: "#f7f8f8",
    borderRadius: 12,
    padding: 14,
    justifyContent: "center",
  },
  dateText: {
    fontSize: 15,
    color: "#1d1617",
    fontFamily: "Poppins-Regular",
  },
  fabButton: {
    position: "absolute",
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: "center",
    alignItems: "center",
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  completeButton: {
    backgroundColor: "#92A3FD",
    bottom: 30,
    right: 100,
  },
  editButton: {
    backgroundColor: "#ff9b63",
    bottom: 30,
    right: 24,
  },
  saveButton: {
    backgroundColor: "#C58BF2",
    bottom: 30,
    right: 24,
  },
});